[package]
edition = "2021"
name = "tkvs-client"
version = "0.1.0"

[dependencies]
anyhow = "1.0.58"
clap = {version = "3.2.16", features = ["derive"]}
tkvs-protos = {path = "../protos"}
tokio = {version = "1.20.1", features = ["full"]}
tonic = "0.8.0"
